#pragma once

#define VENGINE_CLIENT_INTERFACE_VERSION "VEngineClient015"
#define VENGINE_CLIENT_ISPAUSED_OFFSET 84

// Unused
#define CBASECLIENTSTATE_CONNECTIONSTART "?ConnectionStart@CBaseClientState@@UEAAXPEAVINetChannel@@@Z"
#define CBASECLIENTSTATE_GETCLIENTINTERP_AMOUNT "48 83 EC ? 48 8B 0D ? ? ? ? 48 85 C9 75 ? 48 8B 0D"
